# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Abelfubu.WindowsConfigBuilder
PackageVersion: 8.37e1bf5
PackageLocale: en-US
Publisher: Abelfubu
PublisherUrl: https://github.com/abelfubu
PublisherSupportUrl: https://github.com/abelfubu/windows-config-builder/issues
Author: Abel de la Fuente
PackageName: Windows Config Builder
PackageUrl: https://github.com/abelfubu/windows-config-builder
License: MIT
LicenseUrl: https://github.com/abelfubu/windows-config-builder/blob/main/LICENSE
ShortDescription: Automated Windows development environment setup using winget package manager
Description: |
  Windows Config Builder is a tool that automates the setup of a Windows development environment.
  It uses winget to install selected packages and creates configuration files for various tools
  including PowerShell, Starship, Neovim, and more.
Moniker: windows-config-builder
Tags:
- automation
- configuration
- development
- setup
- winget
- windows
ManifestType: defaultLocale
ManifestVersion: 1.5.0
