# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Abelfubu.WindowsConfigBuilder
PackageVersion: 8.37e1bf5
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
- windows-config-builder
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/abelfubu/windows-config-builder/releases/download/v8.37e1bf5/windows-config-builder.exe
  InstallerSha256: 932cb6d0002466c20f07b057469b0f28c1d016d20ed28168562a8ac4cbf6ec50
ManifestType: installer
ManifestVersion: 1.5.0
